name: "Github secret"

on:
  workflow_dispatch:

jobs:
  deployements:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret
        run: |
          echo "MY_TOP_SECRET is ${{ secrets.MY_TOP_SECRET }}"
          echo "i_dont_exist is ${{ secrets.i_dont_exist }}"

      - name: Print secret as an env var
        run: |
          echo "MY_TOP_SECRET is $MY_TOP_SECRET"
        env:
          MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET }}
