# basic workflow pour commencer avec GitHub Actions
name: A Basic Workflow

# actions qui déclenchent le workflow
on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  # permet d'exécuter manuellement le workflow depuis l'interface GitHub
  workflow_dispatch:

# jobs définit les tâches à exécuter
jobs:
  # ce workflow a un seul job appelé "build-app"
  build-app:
    # le type de machine virtuelle à utiliser
    runs-on: ubuntu-latest

    # les étapes représentent les actions à exécuter dans le job
    steps:
      # vérifier le code source du dépôt
      - uses: actions/checkout@v3

      # lancer une commande simple
      - name: run on-line nodejs script
        run: echo hello world !

      # lancer une commande utilisant le shell
      - name: run a multi-line script
        run: |
          echo add other actions build,
          echo test, and deploy your ptoject

  build-api:
    runs-on: windows-latest
    steps:
      - run: echo "Building API"

  build-db:
    needs: build-app
    runs-on: windows-latest
    steps:
      - run: echo "Hello windows"
  package:
    needs: [build-app, build-db]
    runs-on: macos-latest
    steps:
      - run: echo "Hello Macos"
