name: "Custom GITHUB Environment Variables Workflow"

on: workflow_dispatch

jobs:
  custom_GITHUB_ENV_Vars_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV

      - name: Use the value
        id: step_two
        run: |
          echo "${{env.action_state}}" # This will print 'yellow'
